project: 
  type: website

website:
  title: "Data Stack Forge"
  site-url: "http://www.datastackforge.com/"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: blog/index.qmd
  sidebar:
    depth: 2
    collapse: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: true
    code-fold: true
    code-summary: "Click to expand"
    css: styles.css